### ISSUE TITLE
Command: cp -r ../../ios/ScreenShieldKit.framework.  yarn add error

### ISSUE THREAD

**Issue by jinshuokang** [alimek/react-native-screenshield#2]

**Comment by alimek** [comment]
any better way of doing this?

**Comment by patrickml** [comment]
Any updates here?

**Comment by alimek** [comment]
@patrickml do you plan to use this lib for iOS ?

**Comment by patrickml** [comment]
Yes both android and iOS

**Comment by alimek** [comment]
ok, I maybe understand problem now, if you trying to install it for Android only, postinstall is failing because you dont have framework in proper path.

@patrickml do you have framework placed in right directory before do installation ?

**Comment by patrickml** [comment]
Ah... I just looked up ScreenShieldKit. It's a paid service of some kind and this is a wrapper around their software. Is that correct?

**Comment by alimek** [comment]
@patrickml yes, it is correct. As I am aware there is no other lib which is preventing screenshoting on iOS.

On Android you can use flags, but i understand now that postinstall will fail anyway because you dont have iOS file. 
This needs fixing.

**Comment by patrickml** [comment]
Thanks @alimek sounds like its a good place to put how to signup for ScreenShieldKit ;P hopefully they have some affiliate $ for you.

**Comment by alimek** [comment]
We are using this in our internal projects and I am happy to not getting any bonus from ScreenShieldKit guys :-) but you have to contact them directly to get license, its paid per app bundle id around $1000 USD per year.
